site_name: Mana Documentation
theme: readthedocs
pages:
  - Home: 'index.md'
  - Channel:
    - Requesting: 'channel/requesting.md'
  - Modules: 'module/index.md'
  - Module:
    - Bridge: 'module/bridge.md'
    - Invite: 'module/invite.md'
  - About:
    - History: 'about/history.md'
    - Supported Networks: 'about/networks.md'
