site_name: Mana Documentation
site_description: The documentation of the Mana IRC Bot.
site_author: Jamie Mansfield
site_url: http://mana.jamierocks.uk
repo_url: https://github.com/ManaBot/ManaDocs
copyright: Copyright (c) 2016, Jamie Mansfield. Licensed under the MIT license.
theme: readthedocs
pages:
  - Home: 'index.md'
  - Channel:
    - Requesting: 'channel/requesting.md'
  - Modules: 'module/index.md'
  - Module:
    - Bridge: 'module/bridge.md'
    - Invite: 'module/invite.md'
  - About:
    - History: 'about/history.md'
    - Supported Networks: 'about/networks.md'
